version: '2.1'
services:
  web:
   build: ./web
   restart: always
   ports:
     - "8080:80"
   depends_on:
     db:
      condition: service_started
   links:
     - db
   volumes:
      - ./projeto:/var/www/html
      - moodle1:/var/www/moodledata

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   restart: always
   ports:
     - "8888:80"
   environment:
     - PMA_HOST=db
   depends_on:
     db:
      condition: service_started
   links:
     - db
  db:
    image: mysql:5.6
    environment:
      TZ: America/Recife
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dados:/var/lib/mysql


volumes:
  dados:
  moodle1:
